#!/bin/bash

#############################################################################
# Informix gRPC Proxy - Directory Setup Script
#############################################################################

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║                                                            ║"
echo "║        Informix gRPC Proxy - Directory Setup              ║"
echo "║                                                            ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if we're in the right place
if [ ! -f "pom.xml" ]; then
    echo "❌ Error: pom.xml not found."
    echo "   Please run this script from the informix-proxy root directory."
    exit 1
fi

echo "📁 Creating directory structure..."
echo ""

# Create all necessary directories
mkdir -p proto
mkdir -p src/main/java/com/informix/grpc
mkdir -p scripts
mkdir -p lib
mkdir -p clients/nodejs
mkdir -p clients/python
mkdir -p monitoring/grafana/provisioning/datasources
mkdir -p monitoring/grafana/provisioning/dashboards
mkdir -p monitoring/grafana/dashboards
mkdir -p target

echo "✅ Directories created successfully!"
echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    DIRECTORY TREE                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

tree -L 3 -d --charset ascii || ls -R

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                  NEXT STEPS                                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  Copy files to their locations:"
echo ""
echo "   proto/"
echo "   └── informix.proto                          ← API definition"
echo ""
echo "   src/main/java/com/informix/grpc/"
echo "   └── InformixProxyServer.java                ← Main service"
echo ""
echo "   monitoring/"
echo "   ├── prometheus.yml                          ← Metrics config"
echo "   ├── alerts.yml                              ← Alert rules"
echo "   ├── alertmanager-no-slack.yml               ← Notifications (EDIT THIS!)"
echo "   └── grafana/"
echo "       ├── provisioning/"
echo "       │   ├── datasources/datasources.yml"
echo "       │   └── dashboards/dashboards.yml"
echo "       └── dashboards/"
echo "           └── informix-proxy-dashboard.json"
echo ""
echo "   clients/nodejs/"
echo "   ├── package.json"
echo "   └── informix-client.js                      ← Node.js client"
echo ""
echo "   clients/python/"
echo "   ├── requirements.txt"
echo "   └── informix_client.py                      ← Python client"
echo ""
echo "   scripts/"
echo "   └── init-db.sh                              ← Database init"
echo ""
echo "   Root files:"
echo "   ├── pom.xml                                 ← Already exists"
echo "   ├── Dockerfile"
echo "   ├── docker-compose.prod.yml                 ← Full stack config"
echo "   ├── README.md"
echo "   ├── MONITORING.md"
echo "   └── FILE_STRUCTURE.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "2️⃣  Configure email alerts:"
echo ""
echo "   Edit: monitoring/alertmanager-no-slack.yml"
echo "   Lines 11-15:"
echo ""
echo "   smtp_smarthost: 'smtp.gmail.com:587'"
echo "   smtp_from: 'your-email@gmail.com'"
echo "   smtp_auth_username: 'your-email@gmail.com'"
echo "   smtp_auth_password: 'your-app-password'"
echo ""
echo "   Gmail users: Get app password at:"
echo "   https://myaccount.google.com/apppasswords"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "3️⃣  Build the project:"
echo ""
echo "   $ mvn clean package"
echo ""
echo "   This will:"
echo "   • Download Informix JDBC driver from Maven Central"
echo "   • Generate gRPC code from proto file"
echo "   • Compile Java sources"
echo "   • Create fat JAR: target/informix-grpc-proxy-1.0.0.jar"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "4️⃣  Start everything:"
echo ""
echo "   $ docker-compose -f docker-compose.prod.yml up -d"
echo ""
echo "   This starts:"
echo "   • Informix test database (port 9088)"
echo "   • gRPC Proxy (port 50051)"
echo "   • Prometheus (port 9091)"
echo "   • Grafana (port 3000)"
echo "   • Alertmanager (port 9093)"
echo "   • Node Exporter (port 9100)"
echo "   • cAdvisor (port 8080)"
echo "   • Loki (port 3100)"
echo "   • Promtail"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "5️⃣  Access services:"
echo ""
echo "   Grafana:       http://localhost:3000   (admin/admin)"
echo "   Prometheus:    http://localhost:9091"
echo "   Alertmanager:  http://localhost:9093"
echo "   Proxy gRPC:    localhost:50051"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "6️⃣  Test with Node.js:"
echo ""
echo "   $ cd clients/nodejs"
echo "   $ npm install"
echo "   $ node test.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "7️⃣  Test with Python:"
echo ""
echo "   $ cd clients/python"
echo "   $ pip install -r requirements.txt"
echo "   $ python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. ../../proto/informix.proto"
echo "   $ python example.py"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Setup complete! Follow the steps above to get started."
echo ""
echo "📖 For detailed documentation, see:"
echo "   • FILE_STRUCTURE.md  (file organization)"
echo "   • README.md          (full documentation)"
echo "   • MONITORING.md      (observability guide)"
echo ""